config/routes.rb
Rails.application.routes.draw do
  resources :subcategories
  resources :whish_lists
  resources :order_line_items
  resources :orders
  resources :line_items, except: [:new]
  resources :products
  resources :categories
  devise_for :users
  resources :roles
  get 'store/index'

  

  scope "/admin" do
    resources :users
  end

  get 'categories/get_subcategories'

   root 'store#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.nil?
        can :index, :store
        can :read, [Category, Subcategory, Product]
    elsif user.role? "admin"
        can :manage, :all 
    elsif user.role? "user"
        
        can :manage, LineItem
        can [:create, :read], Order
        can :read, [Category, Subcategory, Product]
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :subcategories
	has_many :products
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
	
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :user


before_save :products_total

def products_total
    
	self.total = self.price * self.quantity
	

end


end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	belongs_to :product

	has_many :order_line_items

	after_create :move_line_items

	def move_line_items
		line_items = self.user.line_items
		sum = 0 
		line_items.each do |line_item|
			oli = OrderLineItem.new
			oli.order_id = self.id 
			oli.product_id = line_item.product_id
			oli.quantity = line_item.quantity
			oli.price = line_item.price
			oli.save
			sum += oli.quantity * oli.price
		end

		self.update_attributes(total: sum)
		self.user.line_items.delete_all
	end
end

app/models/order_line_item.rb
class OrderLineItem < ActiveRecord::Base
	belongs_to :order 
	belongs_to :product
end

app/models/permission.rb
class Permission < ActiveRecord::Base
	belongs_to :user
	belongs_to :role
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :line_items
	has_many :orders
	has_many :recent_views
	belongs_to :category
	has_many :whish_lists

	
	belongs_to :category
     belongs_to :subcategory
end

app/models/recent_view.rb
class RecentView < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
end

app/models/role.rb
class Role < ActiveRecord::Base
	validates :name, presence: true

	has_many :permissions
	has_many :users, through: :permissions
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
	has_many :products
	belongs_to :category

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
	has_many :products
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :orders
  has_many :recent_views
  has_many :line_items
  has_many :permissions
  has_many :roles, through: :permissions
  has_many :whish_lists
  has_many :addresses

  accepts_nested_attributes_for :addresses #require multiple users in same form


  after_create :generate_role

  def role?(role)
  	self.roles.pluck(:name).include? role 
  end

  private 

  def generate_role
  	Permission.create(user_id: self.id, role_id: Role.last.id)
  end
end

app/models/whish_list.rb
class WhishList < ActiveRecord::Base
	belongs_to :user
    belongs_to :product
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: [:show, :edit, :update, :destroy]

  # GET /subcategories
  # GET /subcategories.json
  def index
    @subcategories = Subcategory.all
  end

  # GET /subcategories/1
  # GET /subcategories/1.json
  def show
    @products = @subcategory.products.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /subcategories/new
  def new
    @subcategory = Subcategory.new
  end

  # GET /subcategories/1/edit
  def edit
  end

  # POST /subcategories
  # POST /subcategories.json
  def create
    @subcategory = Subcategory.new(subcategory_params)

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully created.' }
        format.json { render :show, status: :created, location: @subcategory }
      else
        format.html { render :new }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcategories/1
  # PATCH/PUT /subcategories/1.json
  def update
    respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @subcategory }
      else
        format.html { render :edit }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1
  # DELETE /subcategories/1.json
  def destroy
    @subcategory.destroy
    respond_to do |format|
      format.html { redirect_to subcategories_url, notice: 'Subcategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcategory
      @subcategory = Subcategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subcategory_params
      params.fetch(:subcategory, {})
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/subcategories/_content.html.erb
<!--Middle Part Start-->
      <div id="content">
        <!--Breadcrumb Part Start-->
        <div class="breadcrumb"> <a href="/">Home</a> &raquo; <a href=""><%= @category.name.capitalize %></a> </div>
        <!--Breadcrumb Part End-->
        <h1><%= @subcategory.name.capitalize %></h1>

        
        <!--Product List Start-->
        <div class="product-list">
          <div>

            <%# @category.products.each do |product| %>
            <% @products.each do |product| %>

            <div class="left">
              <div class="image">
                <a href="<%= product_path(product) %>">
                  <img src="../image/product/ipod_classic_1-162x162.jpg" title="iPad Classic" alt="iPad Classic" />
                </a>
              </div>

              <div class="name">
                <a href="<%= product_path(product) %>"><%= product.name.capitalize %></a>
              </div>

              <div class="description">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto repellendus officia non facere, voluptas dignissimos optio deleniti iste qui eius.
              </div>

              <div class="price">
                <span class="price-tax"> INR <%= product.price %> </span> 
              </div>
              
              <div class="rating">
                <img src="../image/stars-4.png" alt="Based on 1 reviews." />
              </div>

              <div class="cart">

                <input type="button" class="button" onClick="addToCart('42');" value="Add to Cart">

                <div class="wishlist">
                  <a onClick="addToWishList('42');">Add to Wish List</a>
                </div>
                
              </div>
            </div>
          </div>
          <div>
          <% end %>
          <%= will_paginate @products %>
          </div>
        </div>
        <!--Product List End-->
        
      </div>
      <!--Middle Part End-->
      <div class="clear"></div>
    </div>

app/views/subcategories/_form.html.erb
<%= form_for(@subcategory) do |f| %>
  <% if @subcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

      <ul>
      <% @subcategory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subcategories/_left_side_bar.html.erb
<!--Category Start -->
        <div class="box">
          <div class="box-heading">SubCategories</div>
          <div class="box-content box-category">
            <ul id="cat_accordion">
            
            <% Subcategory.all.each do |category| %>
              <li>
                <% if category.name == @subcategory.name %>
                    <a class="active" href="<%= subcategory_path(category) %>"><%= category.name.capitalize %></a> 
                <% else %>
                  <a href="<%= subcategory_path(category) %>"><%= category.name.capitalize %></a> 
                <% end %>
                

                <span class="down"></span>
                <ul>
                
                
                </ul>
              </li>
            <% end %>
              
            </ul>
          </div>
        </div>
        <script type="text/javascript" src="js/jquery.dcjqaccordion.js"></script>
        <!--Category End -->
        <!--Refine Search Start-->
        <div class="box">
          <div class="box-heading">Refine Search</div>
          <div class="box-content">
            <ul class="box-filter">
              <li><span id="filter-group">Price</span>
                <ul>
                  <li>
                    <input type="checkbox" value="3" id="filter3" />
                    <label for="filter3">$0 - $100 (1)</label>
                  </li>
                  <li>
                    <input type="checkbox" value="4" id="filter4" />
                    <label for="filter4">$100 - $500 (5)</label>
                  </li>
                  <li>
                    <input type="checkbox" value="5" id="filter5" />
                    <label for="filter5">$500 - $1000 (1)</label>
                  </li>
                  <li>
                    <input type="checkbox" value="6" id="filter6" />
                    <label for="filter6">$1000 - $1500 (0)</label>
                  </li>
                </ul>
              </li>
            </ul>
            <a id="button-filter" class="button">Refine Search</a> </div>
        </div>
        <!--Refine Search End-->
        <!--Latest Product Start-->
        <div class="box">
          <div class="box-heading">Latest</div>
          <div class="box-content">
            <div class="box-product">
              <div class="flexslider">
                <ul class="slides">
                  
                  <% @subcategory.products.order('created_at DESC').limit(5).each do |product| %>
                  <li>
                    <div class="slide-inner">
                      <div class="image">
                        <a href="<%= product_path(product) %>">
                          <img src="../image/product/sony_vaio_1-45x45.jpg" alt="Friendly Jewelry" />
                        </a>
                      </div>

                      <div class="name">
                        <%= link_to product.name.capitalize, product_path(product) %>
                      </div>

                      <div class="price">INR <%= product.price %></div>
                      <div class="clear"></div>
                    </div>
                  </li>
                  <% end %>

                  
                </ul>
              </div>
            </div>
          </div>
        </div>
        <!--Latest Product End-->
        <!--Banner Start-->
        <div class="banner">
          <div><a href="#"><img src="../image/product/small-banner1-220x350.jpg" alt="banner" title="banner" /></a></div>
        </div>
        <!--Banner End-->

app/views/subcategories/edit.html.erb
<h1>Editing Subcategory</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcategory %> |
<%= link_to 'Back', subcategories_path %>

app/views/subcategories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subcategories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subcategories.each do |subcategory| %>
      <tr>
        <td><%= link_to 'Show', subcategory %></td>
        <td><%= link_to 'Edit', edit_subcategory_path(subcategory) %></td>
        <td><%= link_to 'Destroy', subcategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subcategory', new_subcategory_path %>

app/views/subcategories/new.html.erb
<h1>New Subcategory</h1>

<%= render 'form' %>

<%= link_to 'Back', subcategories_path %>

app/views/subcategories/show.html.erb
<p id="notice"><%= notice %></p>

<div id="column-left">
			<%= render 'left_side_bar' %> 
    </div>


    <%= render 'content' %>

<%= link_to 'Edit', edit_subcategory_path(@subcategory) %> |
<%= link_to 'Back', subcategories_path %>