config/routes.rb
Rails.application.routes.draw do
  resources :subcategories
  resources :whish_lists
  resources :order_line_items
  resources :orders
  resources :line_items, except: [:new]
  resources :products
  resources :categories
  devise_for :users
  resources :roles
  get 'store/index'

  

  scope "/admin" do
    resources :users
  end

  get 'categories/get_subcategories'

   root 'store#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.nil?
        can :index, :store
        can :read, [Category, Subcategory, Product]
    elsif user.role? "admin"
        can :manage, :all 
    elsif user.role? "user"
        
        can :manage, LineItem
        can [:create, :read], Order
        can :read, [Category, Subcategory, Product]
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :subcategories
	has_many :products
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
	
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :user


before_save :products_total

def products_total
    
	self.total = self.price * self.quantity
	

end


end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	belongs_to :product

	has_many :order_line_items

	after_create :move_line_items

	def move_line_items
		line_items = self.user.line_items
		sum = 0 
		line_items.each do |line_item|
			oli = OrderLineItem.new
			oli.order_id = self.id 
			oli.product_id = line_item.product_id
			oli.quantity = line_item.quantity
			oli.price = line_item.price
			oli.save
			sum += oli.quantity * oli.price
		end

		self.update_attributes(total: sum)
		self.user.line_items.delete_all
	end
end

app/models/order_line_item.rb
class OrderLineItem < ActiveRecord::Base
	belongs_to :order 
	belongs_to :product
end

app/models/permission.rb
class Permission < ActiveRecord::Base
	belongs_to :user
	belongs_to :role
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :line_items
	has_many :orders
	has_many :recent_views
	belongs_to :category
	has_many :whish_lists

	
	belongs_to :category
     belongs_to :subcategory
end

app/models/recent_view.rb
class RecentView < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
end

app/models/role.rb
class Role < ActiveRecord::Base
	validates :name, presence: true

	has_many :permissions
	has_many :users, through: :permissions
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
	has_many :products
	belongs_to :category

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
	has_many :products
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :orders
  has_many :recent_views
  has_many :line_items
  has_many :permissions
  has_many :roles, through: :permissions
  has_many :whish_lists
  has_many :addresses

  accepts_nested_attributes_for :addresses #require multiple users in same form


  after_create :generate_role

  def role?(role)
  	self.roles.pluck(:name).include? role 
  end

  private 

  def generate_role
  	Permission.create(user_id: self.id, role_id: Role.last.id)
  end
end

app/models/whish_list.rb
class WhishList < ActiveRecord::Base
	belongs_to :user
    belongs_to :product
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @line_item = LineItem.new
    @whish_list = WhishList.new
    RecentView.create(product_id: @product.id, user_id: current_user.id) if current_user
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :category_id, :featured, :subcategory_id)
    end

  

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_content.html.erb
<!--Middle Part Start-->
      <div id="content">

        <div class="breadcrumb"> 
          <a href="index.html">Home</a> &raquo; 
          <%= link_to @product.category.name.capitalize, category_path(@product.category) %> &raquo;
          <%= link_to @product.subcategory.name.capitalize, subcategory_path(@product.subcategory) %> &raquo;
      
          <a href="#"><%= @product.name.capitalize %></a> 
        </div>

        <h1><%= @product.name.capitalize %></h1>



        <div class="product-info">
          <div class="left">

            <div class="image">
              <a href="../image/product/canon_eos_5d_1-500x500.jpg" title="Canon EOS 5D" class="cloud-zoom colorbox" id='zoom1' rel="adjustX: 0, adjustY:0, tint:'#000000',tintOpacity:0.2, zoomWidth:360, position:'inside', showTitle:false">
                <img src="../image/product/canon_eos_5d_1-350x350.jpg" title="Canon EOS 5D" alt="Canon EOS 5D" id="image" /><span id="zoom-image"><i class="zoom_bttn"></i> Zoom</span>
              </a>
            </div>

             <div class="image-additional">

                <a href="../image/product/canon_eos_5d_1-500x500.jpg" title="Canon EOS 5D" class="cloud-zoom-gallery" rel="useZoom: 'zoom1', smallImage: '../image/product/canon_eos_5d_1-350x350.jpg' ">
                  <img src="../image/product/canon_eos_5d_1-350x350.jpg" width="62" title="Canon EOS 5D" alt="Canon EOS 5D" />
                </a> 

                <a href="../image/product/canon_eos_5d_3-500x500.jpg" title="Canon EOS 5D" class="cloud-zoom-gallery" rel="useZoom: 'zoom1', smallImage: '../image/product/canon_eos_5d_3-350x350.jpg' ">
                  <img src="../image/product/canon_eos_5d_3-350x350.jpg" width="62" title="Canon EOS 5D" alt="Canon EOS 5D" />
                </a> 

                <a href="../image/product/canon_eos_5d_2-500x500.jpg" title="Canon EOS 5D" class="cloud-zoom-gallery" rel="useZoom: 'zoom1', smallImage: '../image/product/canon_eos_5d_2-350x350.jpg' ">
                  <img src="../image/product/canon_eos_5d_2-350x350.jpg" width="62" title="Canon EOS 5D" alt="Canon EOS 5D" />
                </a> 
              </div>

            
          </div>
          <div class="right">
            <div class="description"> <span>Category:</span> 
            <%= link_to @product.category.name.capitalize, category_path(@product.category) %>
            <br />
              <span>Product Code:</span> SKU <%= @product.id + 12345 %><br />
              <span>Reward Points:</span> 200<br />
              <span>Availability:</span> In Stock</div>
            <div class="price">Price: <span class="price-new">INR <%= @product.price %></span> <br />
            </div>
            
            </div>
            <div class="cart">
              <div>


                <div class="qty"> 
                  <%= form_for @line_item do |f| %>
                    <strong>Qty:</strong>
                      <a class="qtyBtn mines" href="javascript:void(0);">-</a>
                      <%= f.text_field :quantity, class: "w30", value: 1, size: 2, id: "qty" %>

                    <a class="qtyBtn plus" href="javascript:void(0);">+</a> 
                 
                  <div class="clear"></div>
                </div>

                  <%= f.hidden_field :product_id, value: @product.id %>
                  <%= f.hidden_field :price, value: @product.price %>   
                <%= f.submit "Add To Cart", class: "button" %>

                <% end %>
              </div>


              <div>
                <a href="#" class="wishlist" >Add to Wish List</a>
              </div>
            </div>

            <div class="review">
              <div><img src="../image/stars-3.png" alt="2 reviews" />&nbsp;&nbsp;<a onClick="$('a[href=\'#tab-review\']').trigger('click');">0 reviews</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a onClick="$('a[href=\'#tab-review\']').trigger('click');">Write a review</a></div>
            </div>
            <!-- AddThis Button BEGIN -->
            <div class="addthis_toolbox addthis_default_style "> <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a> <a class="addthis_button_tweet"></a> <a class="addthis_button_google_plusone" g:plusone:size="medium"></a> <a class="addthis_counter addthis_pill_style"></a> </div>
            <script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=xa-506f325f57fbfc95"></script>
            <!-- AddThis Button END -->
          </div>
        </div>
        <!-- Description and Reviews Tab Start -->
        <div id="tabs" class="htabs"> <a href="#tab-description">Description</a> <a href="#tab-review">Reviews (0)</a> </div>
        <div id="tab-description" class="tab-content">
          <p><strong>Revolutionary multi-touch interface.</strong><br>
            iPod touch features the same multi-touch screen technology as iPhone. Pinch to zoom in on a photo. Scroll through your songs and videos with a flick. Flip through your library by album artwork with Cover Flow.</p>
          <p><strong>Gorgeous 3.5-inch widescreen display.</strong><br>
            Watch your movies, TV shows, and photos come alive with bright, vivid color on the 320-by-480-pixel display.</p>
          <p><strong>Music downloads straight from iTunes.</strong><br>
            Shop the iTunes Wi-Fi Music Store from anywhere with Wi-Fi.1 Browse or search to find the music youre looking for, preview it, and buy it with just a tap.</p>
          <p><strong>Surf the web with Wi-Fi.</strong><br>
            Browse the web using Safari and watch YouTube videos on the first iPod with Wi-Fi built in<br>
            &nbsp;</p>
        </div>
        <div id="tab-review" class="tab-content">
          <div id="review"></div>
          <h2 id="review-title">Write a review</h2>
          <br />
          <b>Your Name:</b><br />
          <input type="text" name="name" value="" />
          <br />
          <br />
          <b>Your Review:</b>
          <textarea name="text" cols="40" rows="8" style="width: 98%;"></textarea>
          <span style="font-size: 11px;"><span style="color: #FF0000;">Note:</span> HTML is not translated!</span><br />
          <br />
          <b>Rating:</b> <span>Bad</span>&nbsp;
          <input type="radio" name="rating" value="1" />
          &nbsp;
          <input type="radio" name="rating" value="2" />
          &nbsp;
          <input type="radio" name="rating" value="3" />
          &nbsp;
          <input type="radio" name="rating" value="4" />
          &nbsp;
          <input type="radio" name="rating" value="5" />
          &nbsp;<span>Good</span><br />
          <br />
          <b>Enter the code in the box below:</b><br />
          <input type="text" name="captcha" value="" />
          <br />
          <br />
          <img src="index.php?route=product/product/captcha" alt="" id="captcha" /><br />
          <br />
          <div class="buttons">
            <div class="right"><a id="button-review" class="button">Continue</a></div>
          </div>
        </div>
        <script>
  $(document).ready(function(){
  $('#tabs a').tabs();
  });
  </script>
        <!-- Description and Reviews Tab Start -->
        <!--Related Product Start-->
        <div class="box">
          <div class="box-heading">Related Products (11)</div>
          <div class="box-content">
            <div class="box-product">
              <div class="flexslider" id="related_pro">
                <ul class="slides">

                <% @product.category.products.order('created_at DESC').limit(5).each do |product| %>
                    <li>
                      <div class="slide-inner">
                        <div class="image">
                          <a href="<%= product_path(product) %>">
                            <img src="../image/product/sony_vaio_1-45x45.jpg" alt="Friendly Jewelry" />
                          </a>
                        </div>
                        <div class="name">
                          <a href="<%= product_path(product) %>"><%= product.name.capitalize %></a>
                        </div>
                        <div class="price">INR <%= product.price %></div>
                        <div class="cart">
                          <input type="button" value="Add to Cart" class="button" />
                      </div>
                        <div class="clear"></div>
                      </div>
                    </li>

                  <% end %>

                </ul>
              </div>
            </div>
          </div>
        </div>
        <script type="text/javascript">
(function() {
  // store the slider in a local variable
  var $window = $(window),
      flexslider;
  // tiny helper function to add breakpoints
  function getGridSize() {
    return (window.innerWidth < 320) ? 1 :
		   (window.innerWidth < 600) ? 2 :
		   (window.innerWidth < 800) ? 3 :
           (window.innerWidth < 900) ? 3 : 4;
  }
  $window.load(function() {
    $('#content #related_pro').flexslider({
      animation: "slide",
      animationLoop: false,
	  slideshow: false,
      itemWidth: 210,
      minItems: getGridSize(), // use function to pull in initial value
      maxItems: getGridSize() // use function to pull in initial value
    });
  });
}());
</script>
        <!--Related Product End-->
      </div>
      <!--Middle Part End-->
      <div class="clear"></div>
      </div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Category" %>
  </div>

  <div class="field" id="subCategoryId">
    <%= f.label :subcategory_id  %><br>
    <%= f.collection_select :subcategory_id, Subcategory.all, :id, :name, prompt: "Select Sub Category" %>
  </div>
  


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_left_navigation.html.erb
<!--Left Part-->
      <div id="column-left">
        <!--Bestsellers Part Start-->
        <div class="box">
          <div class="box-heading">Bestsellers</div>
          <div class="box-content">
            <div class="box-product">
              <div class="flexslider">
                <ul class="slides">

                <% Product.order("RANDOM()").limit(5).each do |product| %>
                    <li>
                      <div class="slide-inner">
                        <div class="image">
                          <a href="<%= product_path(product) %>">
                            <img src="../image/product/sony_vaio_1-45x45.jpg" alt="Friendly Jewelry" />
                          </a>
                        </div>
                        <div class="name">
                          <a href="<%= product_path(product) %>"><%= product.name.capitalize %></a>
                        </div>
                        <div class="price">INR <%= product.price %></div>
                        <div class="clear"></div>
                      </div>
                    </li>

                  <% end %>

                  
                </ul>
              </div>
            </div>
          </div>
        </div>
        <!--Bestsellers Part End-->
        <!--Latest Product Start-->
        <div class="box">
          <div class="box-heading">Latest</div>
          <div class="box-content">
            <div class="box-product">
              <div class="flexslider">
                <ul class="slides">


                 <% @product.category.products.order('created_at DESC').limit(5).each do |product| %>
                    <li>
                      <div class="slide-inner">
                        <div class="image">
                          <a href="<%= product_path(product) %>">
                            <img src="../image/product/sony_vaio_1-45x45.jpg" alt="Friendly Jewelry" />
                          </a>
                        </div>
                        <div class="name">
                          <a href="<%= product_path(product) %>"><%= product.name.capitalize %></a>
                        </div>
                        <div class="price">INR <%= product.price %></div>
                        <div class="clear"></div>
                      </div>
                    </li>

                  <% end %>


                  
                </ul>
              </div>
            </div>
          </div>
        </div>
        <!--Latest Product End-->
        <!--Banner Start-->
        <div class="banner">
          <div><a href="#"><img src="../image/product/small-banner1-220x350.jpg" alt="banner" title="banner" /></a></div>
        </div>
        <!--Banner End-->
      </div>
      <!--Left End-->

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.category.name %></td>
        <td><%= link_to 'Show', product %></td>
        <% if can? :update, product %>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <% end %>

        <% if can? :destroy, product %>
           <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Product.new %>
  <%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<%= render 'left_navigation' %>

<%= render 'content' %>

























<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category.name %>
</p>

<%# form_for @line_item do |f| %>

<%# f.label :quantity %>
<%# f.select :quantity,[1,2, 3, 4, 5,6,7, 8, 9, 10] %><br/>

<%# f.hidden_field :product_id, value: @product.id %>
<%# f.hidden_field :price, value: @product.price %> 

<%# f.submit "Add To Cart" %>

<%# end %>

<%# form_for @whish_list do |f| %>
<%# f.hidden_field :product_id, value: @product.id %>
<%# f.submit "Add To whishlist" %>
<%# end %>



<%# if can? :update, @product %>
	<%# link_to 'Edit', edit_product_path(@product) %> |
<%# end %>

<%# link_to 'Back', products_path %>

<br/><br/>

<h3>Recently Viewd</h3>
<ul>
<%# current_user.recent_views.order('created_at DESC').limit(5).each do |rv| %>
	<li><%# rv.product.name %></li>
<%# end %>
</ul>
 -->