config/routes.rb
Rails.application.routes.draw do
  resources :subcategories
  resources :whish_lists
  resources :order_line_items
  resources :orders
  resources :line_items, except: [:new]
  resources :products
  resources :categories
  devise_for :users
  resources :roles
  get 'store/index'

  

  scope "/admin" do
    resources :users
  end

  get 'categories/get_subcategories'

   root 'store#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.nil?
        can :index, :store
        can :read, [Category, Subcategory, Product]
    elsif user.role? "admin"
        can :manage, :all 
    elsif user.role? "user"
        
        can :manage, LineItem
        can [:create, :read], Order
        can :read, [Category, Subcategory, Product]
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :subcategories
	has_many :products
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
	
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :user


before_save :products_total

def products_total
    
	self.total = self.price * self.quantity
	

end


end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	belongs_to :product

	has_many :order_line_items

	after_create :move_line_items

	def move_line_items
		line_items = self.user.line_items
		sum = 0 
		line_items.each do |line_item|
			oli = OrderLineItem.new
			oli.order_id = self.id 
			oli.product_id = line_item.product_id
			oli.quantity = line_item.quantity
			oli.price = line_item.price
			oli.save
			sum += oli.quantity * oli.price
		end

		self.update_attributes(total: sum)
		self.user.line_items.delete_all
	end
end

app/models/order_line_item.rb
class OrderLineItem < ActiveRecord::Base
	belongs_to :order 
	belongs_to :product
end

app/models/permission.rb
class Permission < ActiveRecord::Base
	belongs_to :user
	belongs_to :role
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :line_items
	has_many :orders
	has_many :recent_views
	belongs_to :category
	has_many :whish_lists

	
	belongs_to :category
     belongs_to :subcategory
end

app/models/recent_view.rb
class RecentView < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
end

app/models/role.rb
class Role < ActiveRecord::Base
	validates :name, presence: true

	has_many :permissions
	has_many :users, through: :permissions
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
	has_many :products
	belongs_to :category

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
	has_many :products
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :orders
  has_many :recent_views
  has_many :line_items
  has_many :permissions
  has_many :roles, through: :permissions
  has_many :whish_lists
  has_many :addresses

  accepts_nested_attributes_for :addresses #require multiple users in same form


  after_create :generate_role

  def role?(role)
  	self.roles.pluck(:name).include? role 
  end

  private 

  def generate_role
  	Permission.create(user_id: self.id, role_id: Role.last.id)
  end
end

app/models/whish_list.rb
class WhishList < ActiveRecord::Base
	belongs_to :user
    belongs_to :product
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = current_user.line_items
    @order = Order.new
    if params[:coupon]
      @coupon_code = params[:coupon]
      @coupon = Coupon.find_by_coupon_code_and_status(params[:coupon], 'Active')
    end
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @line_item = LineItem.new(line_item_params)
    @line_item.user_id = current_user.id
    @line_item.price = Product.find(@line_item.product_id).price 
    respond_to do |format|
      if @line_item.save
        format.html { redirect_to line_items_path, notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to line_items_path, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :user_id, :quantity, :price)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<% if @line_items.empty? %>

  <h1> Your cart is empty </h1>
   <p>Continue Shopping <%= link_to "here", products_path %></p>
  <% else %>

  <% sum = 0 %>
    <% @line_items.each do |line_item| %>
     
      <% sum += line_item.quantity * line_item.price %>
  <% end %>
 
<!--Breadcrumb Part Start-->
        <div class="breadcrumb"> <a href="index.html">Home</a> » <a href="">Shopping Cart</a></div>
        <!--Breadcrumb Part End-->
        <h1>Shopping Cart &nbsp;(11.00kg)</h1>
        <form enctype="multipart/form-data" method="post" action="">
          <div class="cart-info">
            <table>
              <thead>
                <tr>
                  <td class="image">Image</td>
                  <td class="name">Product Name</td>
                  <td class="model">Category</td>
                  <td class="quantity">Quantity</td>
                  <td class="price">Unit Price</td>
                  <td class="total">Total</td>
                </tr>
              </thead>
              <tbody>
              
              <% @line_items.each do |line_item| %>
                <tr>
                    <td class="image"><a href="<%= product_path(line_item.product) %>"><img src="../image/product/ipod_classic_1-45x45.jpg" alt="iPad Classic" /></a></td>
                    <td class="name"><a href="<%= product_path(line_item.product) %>"><%= line_item.product.name.capitalize %></a></td>
                    <td class="model"><%= line_item.product.category.name.capitalize %></td>

                    <td class="quantity">
                     <%= form_for line_item do |f| %>
                     <%= f.text_field :quantity, size: 1, class: "w30" %>
                      &nbsp;
                     
                      <%= f.submit "update", :type => :image, :src=>"image/update.png" %>

                      <% end %>

                      <%= link_to line_item, method: :delete, data: {confirm: "Are you sure?"} do %>
                          <img title="Remove" alt="Remove" src="../image/remove.png"></a>
                      <% end %>
                      &nbsp;</td>


                    <td class="price">INR <%= line_item.product.price %></td>
                    <td class="total">INR <%= line_item.quantity * line_item.product.price %></td>
                </tr>
                <% end %>
                
              </tbody>
            </table>
          </div>
        </form>
        <h2>What would you like to do next?</h2>
        <div class="content">
          <p>Choose if you have a discount code or reward points you want to use or would like to estimate your delivery cost.</p>
          <div class="accordion">
            <div class="accordion-heading">Use Coupon Code</div>
            <div class="accordion-content">
              <div class="content" id="coupon">
                <form enctype="multipart/form-data" method="post" action="">
                  Enter your coupon here:&nbsp;
                  <input type="text" value="" name="coupon">
                  &nbsp;
                  <input type="submit" class="button" value="Apply Coupon">
                </form>
              </div>
            </div>
          </div>
          <div class="accordion">
            <div class="accordion-heading">Use Gift Voucher</div>
            <div class="accordion-content">
              <div class="content" id="voucher">
                <form enctype="multipart/form-data" method="post" action="">
                  Enter your gift voucher code here:&nbsp;
                  <input type="text" value="" name="voucher">
                  &nbsp;
                  <input type="submit" class="button" value="Apply Voucher">
                </form>
              </div>
            </div>
          </div>
         
        <div class="cart-total">
          <table id="total">
            <tbody>
             
              <tr>
                <td class="right"><b>Total:</b></td>
                <td class="right">INR <%= sum %></td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="buttons">
          <div class="right">

<%= form_for @order do |f| %>
  <%= f.hidden_field :order_date, value: Date.today %>
  <%= f.submit "Checkout", class: "button" %>
<% end %>


          </div>



          <div class="center"><a class="button" href="#">Continue Shopping</a></div>
        </div>
      </div>
      <!--Middle Part End-->
      <div class="clear"></div>

      

      <%= form_tag({url: line_items_path}, {method: :get}) do %>

        <%= label_tag :coupon %>
        <%= text_field_tag :coupon %>
      <%= submit_tag %>
      <% end %>

      

<% end %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @line_item.user_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @line_item.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @line_item.price %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>